# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/make_llm',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/make_llm',
                'lib_path': 'make_llm'},
  'syms': {'make_llm.core': {'make_llm.core.foo': ('core.html#foo', 'make_llm/core.py')}}}
