"""In this blog post I'll explore the structure of token embeddings in large language models."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_token_encoding.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_token_encoding.ipynb 5
import fastai
import fastai.torch_core
import numpy as np
import torch
import matplotlib.pyplot as plt
from transformers import AutoModelForCausalLM, AutoTokenizer
import gc
import pandas as pd
from fastcore.all import *
from IPython.display import display_markdown
